name: infosleuth
description: A powerful info-detective chat & reverse lookup tool

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  file_picker: ^10.1.2
  filepicker_windows: ^2.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/infosleuth_logo.png
